### ISSUE TITLE
Make some pseudo 3D examples (just for fun)

### ISSUE THREAD

**Issue by luizbills** [litecanvas/game-engine#8]
Ideas:

- [x] Animated Cube 
- [ ] First-person

**Comment by luizbills** [comment]
https://www.playfuljs.com/a-first-person-engine-in-265-lines/

**Comment by luizbills** [comment]
https://www.youtube.com/watch?v=p4Iz0XJY-Qk

**Comment by luizbills** [comment]
3D cube added in https://github.com/litecanvas/game-engine/commit/86ee7091365f7a12c7177a772ced3e774354d76a

**Comment by Add00** [comment]
Hello, I've been playing around with your engine and it's quite versatile. I'm working on a ray-casting sample, and I'm also a Hackoberfest participant, could I contribute that to your project?

**Comment by luizbills** [comment]
@Add00 of course!!

**Comment by Add00** [comment]
Thanks, @luizbills, I've pretty much finished my implementation, this is what it looks like so far 
[video.webm](https://github.com/user-attachments/assets/13981e6c-e3fb-4147-9e4d-83746961bccf), I'll make a PR shortly.
