### ISSUE TITLE
Procedural generation feature and sample

### ISSUE THREAD

**Issue by Add00** [litecanvas/game-engine#88]
Hey @luizbills, I've been using your engine to do some basic procedural generation using [Perlin noise](https://en.wikipedia.org/wiki/Perlin_noise). If you would like I can create a sample version for this project. I could also turn it into a usable API as an engine feature or plugin (whichever you think is best).

Currently, i've manged to get 1D and 2D generation, the ultimate goal is to have 3D generation as well:
![image](https://github.com/user-attachments/assets/35bf9883-9105-4e50-9434-6c6218b7b6ac)

**Comment by luizbills** [comment]
I think you could make a stateless library for perlin noise using the same p5.js noise API: https://p5js.org/reference/p5/noise/

You can make it as a dedicated plugin or as part of https://github.com/litecanvas/utils (what you prefer).

**Comment by Add00** [comment]
I'll take a deeper look at the p5 noise API, it looks better then the previous API I was using. Given the general nature of Perlin noise I'll add it as part of the utils plugin.
