### ISSUE TITLE
Make more game examples

### ISSUE THREAD

**Issue by luizbills** [litecanvas/game-engine#9]
- [x] [Tic Tac Toe](https://www.youtube.com/watch?v=GTWrWM1UsnA) (closed by #84)
- [x] [Game of Life](https://www.youtube.com/watch?v=FWSR_7kZuYg) (closed by #77)

**Comment by AttAditya** [comment]
I've raised a PR #77 for task 2, would like if I can be assigned this task completely for finishing task 1 sample as well! 😁

**Comment by Add00** [comment]
Could I work on creating a tic-tac-toe example?

**Comment by luizbills** [comment]
> Could I work on creating a tic-tac-toe example?

Sure.

**Comment by Add00** [comment]
Thanks, I've got the example complete, I'll make a PR now
