### ISSUE TITLE
Game Sample - Connect Four

### ISSUE THREAD

**Issue by cduarte3** [litecanvas/game-engine#90]
# Feature
I would like to try and add a game of connect four into the samples directory or the [games](https://github.com/litecanvas/games) repo.

It may take me some time as I am still new to using this engine, but I will update you with my progress.

Please let me know if this game is something you would want added to the samples. If yes, I can get started as soon as possible.

# Extra
If I am complete with this sooner than I expect to, then I will do my best to contribute in another way, such as adding more tests with PR's as you mentioned to me a few days ago.

**Comment by luizbills** [comment]
> Please let me know if this game is something you would want added to the samples. If yes, I can get started as soon as possible.

Of course! You add in the https://github.com/litecanvas/games

**Comment by cduarte3** [comment]
Sounds goo, will see what I can do!

**Comment by luizbills** [comment]
thanks!
